##
# CONFIG.YML - Some baseline configuration options for the files that will be managed.
# There's a lot of duplication in here, I'd like to find a way to simplify things in the future. -MR
#
# Version History
# => 0.3 Internal testing version (2011-07-11)
# => 0.2 Internal testing version (2011-07-09)
# => 0.1 Internal testing version (2011-07-07)
##
---
svn:
  repo: https://navartssvn01.navarts.local/svn/NavArts.FEBuildScript.Test/
  path: trunk/rake_experiment/
  source: _dev/
  export: _build/
html:
  source: _dev/html/
  export: _build/html/
images:
  source: _dev/img/
  export: _build/img/
stylesheets:
  source: _dev/css/
  export: _build/css/
  manage:
  - project.css
  - print.css
  validate: 
  - project.css
  - print.css
scripts: 
  source: _dev/js/
  export: _build/js/
  manage:
  - project.js
  jslint:
  - project.js