##
# CONFIG.YML - Some baseline configuration options for the files that will be managed.
##
---
versioncontrol:
  svn: 
html:
  source: _dev/html/
  export: _build/html/
images:
  source: _dev/img/
  export: _build/img/
stylesheets:
  source: _dev/css/ 
  export: _build/css/
  manage:
  - project.css
  validate: 
  - project.css
scripts: 
  source: _dev/js/
  export: _build/js/
  manage:
  - project.js
  jslint:
  - project.js
  # SOON...well, maybe eventually anyway...
  # qunit:
  # - project.js